// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiXIsvcYwqRgVzbja3I0CYR16C2apQi0E',
    appId: '1:903996836309:web:21c20e25fe49f8cfad555c',
    messagingSenderId: '903996836309',
    projectId: 'dreme-2b1fe',
    authDomain: 'dreme-2b1fe.firebaseapp.com',
    databaseURL: 'https://dreme-2b1fe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dreme-2b1fe.appspot.com',
    measurementId: 'G-XTK1WFL2NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHsxRwa7cO_yByX0Qclrz_UVVkxOPjq7k',
    appId: '1:903996836309:android:0745a1802a6053d1ad555c',
    messagingSenderId: '903996836309',
    projectId: 'dreme-2b1fe',
    databaseURL: 'https://dreme-2b1fe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dreme-2b1fe.appspot.com',
  );
}
